INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked)VALUES (CAST(random_uuid() AS VARCHAR(36)), 'admin', 'bot', 'bot', '{bcrypt}...', 'admin@example.com', '+380501234567', 'ADMIN', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked)VALUES (CAST(random_uuid() AS VARCHAR(36)), 'manager', 'bot', 'bot', '$2a$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'manager@example.com', '+380661234567', 'MANAGER', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked)VALUES (CAST(random_uuid() AS VARCHAR(36)), 'user1', 'bot', 'bot', '$2a$10$YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 'user1@example.com', '+380731234567', 'USER', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked)VALUES (CAST(random_uuid() AS VARCHAR(36)), 'user2', 'bot', 'bot', '$2a$10$ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ', 'user2@example.com', '+380801234567', 'USER', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked)VALUES (CAST(random_uuid() AS VARCHAR(36)), 'support', 'bot', 'bot', '$2a$10$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'support@example.com', '+380911234567', 'USER', TRUE, 0.00, 0, NULL, FALSE);

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Paris Escape', 'Romantic weekend getaway in the heart of Paris with exquisite cuisine', 1299.99, 'ADVENTURE', 'PLANE', 'FIVE_STARS', 'REGISTERED', DATEADD('DAY',2,CURRENT_DATE), DATEADD('DAY',9,CURRENT_DATE), (SELECT id FROM users WHERE username='admin'), TRUE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Paris Escape'),'en', 'Paris Escape', 'Romantic weekend getaway in the heart of Paris with exquisite cuisine');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Paris Escape'),'uk', 'Втеча до Парижа', 'Романтичний вікенд у самому серці Парижа з вишуканою кухнею');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Tokyo Discovery', 'Immerse yourself in Tokyo`s vibrant urban culture and modern marvels', 899.50, 'CULTURAL', 'TRAIN', 'FOUR_STARS', 'PAID', CURRENT_DATE, DATEADD('DAY',5,CURRENT_DATE), (SELECT id FROM users WHERE username='user1'), FALSE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Tokyo Discovery'),'en', 'Tokyo Discovery', 'Immerse yourself in Tokyo`s vibrant urban culture and modern marvels');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Tokyo Discovery'),'uk', 'Відкриття Токіо', 'Пориньте у яскраву міську культуру Токіо та сучасні дива');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'African Safari', 'Experience an unforgettable journey through the wild African savannah', 1599.75, 'SAFARI', 'PRIVATE_CAR', 'THREE_STARS', 'REGISTERED', DATEADD('DAY',5,CURRENT_DATE), DATEADD('DAY',15,CURRENT_DATE), (SELECT id FROM users WHERE username='manager'), TRUE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='African Safari'),'en', 'African Safari', 'Experience an unforgettable journey through the wild African savannah');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='African Safari'),'uk', 'Африканське сафарі', 'Незабутня подорож через дику савану Африки');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Eco Adventure', 'Sustainable eco-friendly tour with nature trails and minimal impact', 499.99, 'ECO', 'BUS', 'TWO_STARS', 'CANCELED', DATEADD('DAY',-1,CURRENT_DATE), DATEADD('DAY',3,CURRENT_DATE), (SELECT id FROM users WHERE username='support'), FALSE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Adventure'),'en', 'Eco Adventure', 'Sustainable eco-friendly tour with nature trails and minimal impact');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Adventure'),'uk', 'Еко-пригоди', 'Еко-тур з екологічно чистими маршрутами');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Health Retreat', 'Relax at our health resort with rejuvenating treatments', 350.00, 'HEALTH', 'BUS', 'ONE_STAR', 'REGISTERED', DATEADD('DAY', 5,CURRENT_DATE), DATEADD('DAY',12,CURRENT_DATE), (SELECT id FROM users WHERE username='user1'), FALSE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Health Retreat'),'en', 'Health Retreat', 'Relax at our health resort with rejuvenating treatments');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Health Retreat'),'uk', 'Відпочинок для здоров’я', 'Розслабтеся в нашому оздоровчому курорті з процедурами відновлення');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Sports Challenge', 'Participate in thrilling sports events and competitions', 450.00, 'SPORTS', 'TRAIN', 'TWO_STARS', 'REGISTERED', DATEADD('DAY', 9,CURRENT_DATE), DATEADD('DAY',18,CURRENT_DATE), (SELECT id FROM users WHERE username='user2'), FALSE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Sports Challenge'),'en', 'Sports Challenge', 'Participate in thrilling sports events and competitions');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Sports Challenge'),'uk', 'Спортивний виклик', 'Візьміть участь у захоплюючих спортивних подіях та змаганнях');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Leisure Escape', 'Enjoy a luxurious leisure escape with premium services', 1150.00, 'LEISURE', 'PLANE', 'THREE_STARS', 'PAID', DATEADD('DAY', 4,CURRENT_DATE), DATEADD('DAY',14,CURRENT_DATE), (SELECT id FROM users WHERE username='admin'), TRUE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Leisure Escape'),'en', 'Leisure Escape', 'Enjoy a luxurious leisure escape with premium services');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Leisure Escape'),'uk', 'Розкішний відпочинок', 'Насолоджуйтеся преміальними послугами у розкішному турі');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Wild Safari', 'Experience the wild with guided safari tours on majestic landscapes', 1400.00, 'SAFARI', 'SHIP', 'FOUR_STARS', 'REGISTERED', DATEADD('DAY', 7,CURRENT_DATE), DATEADD('DAY',16,CURRENT_DATE), (SELECT id FROM users WHERE username='manager'), FALSE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wild Safari'),'en', 'Wild Safari', 'Experience the wild with guided safari tours on majestic landscapes');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wild Safari'),'uk', 'Дике сафарі', 'Відчуйте дику природу з екскурсіями по величних краєвидах');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Wine Tasting Journey', 'Indulge in exquisite wines and gourmet experiences', 1300.00, 'WINE', 'PRIVATE_CAR', 'FIVE_STARS', 'PAID', DATEADD('DAY', 3,CURRENT_DATE), DATEADD('DAY',9,CURRENT_DATE), (SELECT id FROM users WHERE username='support'), TRUE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wine Tasting Journey'),'en', 'Wine Tasting Journey', 'Indulge in exquisite wines and gourmet experiences');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wine Tasting Journey'),'uk', 'Дегустація вин', 'Насолоджуйтеся вишуканими винами та гастрономічними смаками');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Eco Nature Trek', 'Embark on an eco-friendly trek through pristine nature trails', 550.00, 'ECO', 'JEEPS', 'TWO_STARS', 'CANCELED', CURRENT_DATE, DATEADD('DAY',5,CURRENT_DATE), (SELECT id FROM users WHERE username='user1'), FALSE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Nature Trek'),'en', 'Eco Nature Trek', 'Embark on an eco-friendly trek through pristine nature trails');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Nature Trek'),'uk', 'Еко-похід', 'Вирушайте у подорож по недоторканих природних стежках');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Adventure Expedition', 'Join an adventurous expedition to explore remote landscapes', 999.99, 'ADVENTURE', 'MINIBUS', 'THREE_STARS', 'REGISTERED', DATEADD('DAY', 7,CURRENT_DATE), DATEADD('DAY',19,CURRENT_DATE), (SELECT id FROM users WHERE username='manager'), TRUE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Adventure Expedition'),'en', 'Adventure Expedition', 'Join an adventurous expedition to explore remote landscapes');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Adventure Expedition'),'uk', 'Пригодницька експедиція', 'Вирушайте досліджувати віддалені ландшафти');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Cultural Odyssey', 'Explore historic sites and immerse in diverse cultural experiences', 799.99, 'CULTURAL', 'ELECTRICAL_CARS', 'FOUR_STARS', 'PAID', CURRENT_DATE, DATEADD('DAY',7,CURRENT_DATE), (SELECT id FROM users WHERE username='admin'), FALSE);
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Cultural Odyssey'),'en', 'Cultural Odyssey', 'Explore historic sites and immerse in diverse cultural experiences');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Cultural Odyssey'),'uk', 'Культурна одіссея', 'Дослідіть історичні місця та пориньте у багатокультурний світ');